function doCalculateMultipliersAndSolveOnPeriod(...
  solno,fcnToCall )

fcnToCall(solno,@mfilename,@getFileDir,@getResultsFilepathForMFile,...
  @getResultsFilepath,@exist,@load,@save,@predatorPrey2x1Params,...
  @multipliers_one_system_for_each_monodromy_matrix_column,@myode4,...
  @figure,@fprintf,@display);
end

