function doPlotCombinedFamSolPhaseTrajectories(...
  doPlotCombinedFamSolPhaseTrajectoriesCore )

doPlotCombinedFamSolPhaseTrajectoriesCore(@currentDirName,@load,...
  @getLastRowWithExtremeElementValue,@plot3,@hold,@label,@xlabel,...
  @ylabel,@zlabel,@gca,@set);
end

