function doPlotFamily( doPlotFamilyCore )

doPlotFamilyCore(@mfilename,@getFileDirname,@dir,@load,...
  @getLastRowWithExtremeElementValue,...
  @getSolutionTillMinFirstPredatorDensity,@plot,@hold,@label,...
  @xlabel,@ylabel,@gca,@set);
end

