function doPlotCombinedFamSolPhaseTrajectories(...
  doPlotCombinedFamSolPhaseTrajectoriesCore )

doPlotCombinedFamSolPhaseTrajectoriesCore(@currentDirName,@load,...
  @getLastRowWithExtremeElementValue,@plot3,@hold,@xlabel,@ylabel,...
  @zlabel,@gca,@set);
end

