function doSolve( doSolveCore,solutionResultsFilename,...
  preyDiffusionCoeff,secondPredatorDiffusionCoeff,resourceDeviation,N,...
  tspan,getInitialData,solver )

doSolveCore(solutionResultsFilename,preyDiffusionCoeff,...
  secondPredatorDiffusionCoeff,resourceDeviation,N,tspan,...
  getInitialData,@mfilename,@getFileDirname,@exist,@load,@mkdir,...
  @saveStruct,@predatorPrey2x1Params,solver);
end

