function doSolveOne( doSolveOneCore,solutionResultsFilename,...
  preyDiffusionCoeff,secondPredatorDiffusionCoeff,...
  firstPredatorMortality,resourceDeviation,N,tspan,getInitialData,solver )

doSolveOneCore(solutionResultsFilename,preyDiffusionCoeff,...
  secondPredatorDiffusionCoeff,firstPredatorMortality,...
  resourceDeviation,N,tspan,getInitialData,@mfilename,@getFileDirname,...
  @exist,@load,@mkdir,@saveStruct,@predatorPrey2x1Params,solver);
end

