function [multiplicators,computation_time] = calculate_multiplicators_poincare_section_method( right_parts_of_equations,linearized_system,nspecies,N,w0,tlast,T,tstep,fixed_var_index,fixed_var_value,eps,first_phas_var_index,second_phas_var_index,final_multiplicators_file_path_beginning,intermediate_results_file_path,interp_method )
%CALCULATE_MULTIPLICATORS_POINCARE_SECTION_METHOD Summary of this function goes here
%   Detailed explanation goes here
nvar = nspecies*N;
[multiplicators,computation_time] = multiplicators_poincare_section_method(...
    right_parts_of_equations,@myode4,0:tstep:tlast,w0,nvar,...
    intermediate_results_file_path,...
    fixed_var_index,fixed_var_value,eps,...
    odeset('NonNegative',1:nvar),...
    odeset('OutputFcn',@odephas2,'OutputSel',[first_phas_var_index,...
                                              second_phas_var_index]),...
    interp_method);

if ~isempty(multiplicators)
  final_multiplicators_file_path = strcat(final_multiplicators_file_path_beginning,sprintf('poincare_eps=%f.mat',eps));
  save(final_multiplicators_file_path,'multiplicators','computation_time');
end

end

