function doFindAndSavePointWithMaxPredatorDensities(...
  doFindAndSavePointWithMaxPredatorDensitiesCore,resultsFilename,...
  secondPredatorDiffusionCoeff )

doFindAndSavePointWithMaxPredatorDensitiesCore(resultsFilename,...
  secondPredatorDiffusionCoeff,@mfilename,...
  @getFileDir,@getDirpath,@getResultsFilepath,@exist,@load,@saveStruct,...
  @predatorPrey2x1Params,@figure,@myode4,...
  @getFirstPointWithExtremeVarValues);
end

