function doPlotFamily( doPlotFamilyCore,familyName )

doPlotFamilyCore(familyName,@mfilename,@getFileDirname,@dir,@load,...
  @getLastRowWithExtremeElementValue,...
  @getSolutionTillMinFirstPredatorDensity,@plot,@hold,@label,...
  @xlabel,@ylabel,@gca,@set);
end

