function doPlotFamily( doPlotFamilyCore )

doPlotFamilyCore(@mfilename,@getFileDirname,@dir,@load,...
  @getLastRowWithExtremeElementValue,...
  @getSolutionTillMinFirstPredatorDensity,@subplot,@plot,@hold,@label,...
  @xlabel,@ylabel,@set);
end

