function doSolveTillSteady( solno,tf,doSolveTillSteadyCore )

doSolveTillSteadyCore(solno,tf,@mfilename,@getFileDir,@exist,...
  @getInitialDataToSolveTillSteady,@load,@save,@predatorPrey2x1Params,...
  @myode4,@getFirstPointWithExtremeVarValues,@getLastRow,@getPeriod,...
  @getResultsFilepath,@getSolutionTillMaxPredatorDensities);
end

