function doSolveAndSaveResults( solno,tf,doSolveAndSaveResultsCore )

doSolveAndSaveResultsCore(solno,tf,@mfilename,@getFileDir,...
  @getResultsFilepath,@exist,@getZeroFirstPredatorInitialData,...
  @getCombinedPredatorDensitiesInitialData,@load,@save,...
  @predatorPrey2x1Params,@myode4,@getLastRow,@getPeriod);
end

