function doSolveAll( doSolveAllCore,preyDiffusionCoeff,...
  secondPredatorDiffusionCoeff,firstPredatorMortality,resourceDeviation,...
  N,tspan,solver,nsol,familyName )

doSolveAllCore(preyDiffusionCoeff,secondPredatorDiffusionCoeff,...
  firstPredatorMortality,resourceDeviation,N,tspan,solver,nsol,...
  familyName,@currentDirName,@dir,@solveOne);
end

