function findAndSavePointWithMaxPredatorDensities( resultsFilename,...
  secondPredatorDiffusionCoeff)

doFindAndSavePointWithMaxPredatorDensities(...
  @doFindAndSavePointWithMaxPredatorDensitiesCore,resultsFilename,...
  secondPredatorDiffusionCoeff);
end

