function solveOne( solutionResultsFilename,...
  preyDiffusionCoeff,secondPredatorDiffusionCoeff,...
  firstPredatorMortality,resourceDeviation,N,tspan,getInitialData,solver )

doSolveOne(@doSolveOneCore,solutionResultsFilename,preyDiffusionCoeff,...
  secondPredatorDiffusionCoeff,firstPredatorMortality,resourceDeviation,...
  N,tspan,getInitialData,solver);
end

